DefaultTeam: DefaultKey
DumpTeam: randomkey

R1HT01: REPLACE_TEAM
R1HT02: REPLACE_TEAM
R1HT03: REPLACE_TEAM
R1HT04: REPLACE_TEAM
R1HT05: REPLACE_TEAM
R1HT06: REPLACE_TEAM
R1HT07: REPLACE_TEAM
R1HT08: REPLACE_TEAM
R1HT09: REPLACE_TEAM
R1HT10: REPLACE_TEAM
R2HT01: REPLACE_TEAM
R2HT02: REPLACE_TEAM
R2HT03: REPLACE_TEAM
R2HT04: REPLACE_TEAM
R2HT05: REPLACE_TEAM
R2HT06: REPLACE_TEAM
R2HT07: REPLACE_TEAM
R2HT08: REPLACE_TEAM
R2HT09: REPLACE_TEAM
R2HT10: REPLACE_TEAM
R3HT01: REPLACE_TEAM
R3HT02: REPLACE_TEAM
R3HT03: REPLACE_TEAM
R3HT04: REPLACE_TEAM
R3HT05: REPLACE_TEAM
R3HT06: REPLACE_TEAM
R3HT07: REPLACE_TEAM
R3HT08: REPLACE_TEAM
R3HT09: REPLACE_TEAM
R3HT10: REPLACE_TEAM
